In [1]:
import pandas as pd

### Reading CSV File

In [8]:
ecom_df = pd.read_csv('../Pandas/sample_data/Ecommerce_Purchases.csv')
ecom_df.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

### Qn 1
- Fetch the first 3 rows and the last 7 rows of the dataset.

In [10]:
first_three_row = ecom_df.head(3)
first_three_row

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95

In [11]:
last_seven_row = ecom_df.tail(7)
last_seven_row

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

### Qn 2
- How many rows and columns are there in our dataset?

In [13]:
rows = ecom_df.shape[0]
col = ecom_df.shape[1]

print('Rows: ', rows)
print('Cols: ', col)

Rows:  10000
Cols:  14

### Qn 3
- Find the highest and lowest purchase prices.

In [18]:
max_price = ecom_df.max()['Purchase Price']
max_price

99.99

### Qn 4
- Calculate the average purchase price.

In [21]:
avg_price = ecom_df['Purchase Price'].mean()
avg_price

50.347302

### Qn 5
- Fetch all job titles that contain the word "Engineer".

In [28]:
import re
ptrn = r"\b(Engineer|engineer)\b"
df_eng = ecom_df['Job']
list = []
for job in df_eng:
    if re.search(ptrn, job):
        list.append(job)
    
list

['Drilling engineer',
 'Drilling engineer',
 'Mechanical engineer',
 'Engineer, broadcasting (operations)',
 'Engineer, agricultural',
 'Engineer, civil (consulting)',
 'Engineer, materials',
 'Engineer, land',
 'Engineer, water',
 'Technical sales engineer',
 'Engineer, aeronautical',
 'Engineer, chemical',
 'Engineer, building services',
 'Energy engineer',
 'Water engineer',
 'Software engineer',
 'Engineer, civil (consulting)',
 'Engineer, civil (contracting)',
 'Structural engineer',
 'Mining engineer',
 'Engineer, energy',
 'Manufacturing systems engineer',
 'Control and instrumentation engineer',
 'Consulting civil engineer',
 'Engineer, structural',
 'Site engineer',
 'Engineer, building services',
 'Mining engineer',
 'Engineer, maintenance (IT)',
 'Consulting civil engineer',
 'Petroleum engineer',
 'Engineer, maintenance',
 'Communications engineer',
 'Energy engineer',
 'Civil engineer, consulting',
 'Engineer, production',
 'Mining engineer',
 'Engineer, energy',
 'Engineer, communications',
 'Engineer, drilling',
 'Engineer, control and instrumentation',
 'Engineer, site',
 'Automotive engineer',
 'Contracting civil engineer',
 'Maintenance engineer',
 'Broadcast engineer',
 'Engineer, manufacturing',
 'Structural engineer',
 'Energy engineer',
 'Petroleum engineer',
 'Agricultural engineer',
 'Petroleum engineer',
 'Engineer, petroleum',
 'Engineer, maintenance',
 'Engineer, civil (consulting)',
 'Electrical engineer',
 'Engineer, maintenance',
 'Manufacturing engineer',
 'Engineer, land',
 'Technical sales engineer',
 'Contracting civil engineer',
 'Control and instrumentation engineer',
 'Chemical engineer',
 'Water engineer',
 'Software engineer',
 'Drilling engineer',
 'Biomedical engineer',
 'Broadcast engineer',
 'Engineer, civil (consulting)',
 'Civil engineer, contracting',
 'Maintenance engineer',
 'Engineer, broadcasting (operations)',
 'Materials engineer',
 'Electrical engineer',
 'Agricultural engineer',
 'Network engineer',
 'Engineer, structural',
 'Maintenance engineer',
 'Engineer, electrical',
 'Engineer, building services',
 'Contracting civil engineer',
 'Engineer, manufacturing',
 'Technical sales engineer',
 'Chemical engineer',
 'Petroleum engineer',
 'Engineer, automotive',
 'Contracting civil engineer',
 'Engineer, control and instrumentation',
 'Engineer, manufacturing systems',
 'Petroleum engineer',
 'Site engineer',
 'Engineer, production',
 'Network engineer',
 'Energy engineer',
 'Building services engineer',
 'Drilling engineer',
 'Site engineer',
 'Control and instrumentation engineer',
 'Engineer, agricultural',
 'Engineer, land',
 'Manufacturing engineer',
 'Contracting civil engineer',
 'Production engineer',
 'Control and instrumentation engineer',
 'Production engineer',
 'Chemical engineer',
 'Engineer, maintenance',
 'Engineer, maintenance (IT)',
 'Engineer, water',
 'Drilling engineer',
 'Control and instrumentation engineer',
 'Engineer, maintenance (IT)',
 'Engineer, land',
 'Engineer, communications',
 'Software engineer',
 'Engineer, land',
 'Engineer, energy',
 'Production engineer',
 'Control and instrumentation engineer',
 'Engineer, mining',
 'Engineer, manufacturing',
 'Engineer, water',
 'Manufacturing systems engineer',
 'Maintenance engineer',
 'Engineer, electronics',
 'Engineer, civil (contracting)',
 'Engineer, site',
 'Engineer, land',
 'Communications engineer',
 'Manufacturing engineer',
 'Engineer, aeronautical',
 'Materials engineer',
 'Site engineer',
 'Engineer, civil (contracting)',
 'Engineer, agricultural',
 'Manufacturing systems engineer',
 'Engineer, broadcasting (operations)',
 'Engineer, manufacturing systems',
 'Drilling engineer',
 'Production engineer',
 'Technical sales engineer',
 'Engineer, maintenance (IT)',
 'Engineer, control and instrumentation',
 'Broadcast engineer',
 'Engineer, production',
 'Engineer, civil (contracting)',
 'Engineer, energy',
 'Control and instrumentation engineer',
 'Civil engineer, consulting',
 'Engineer, electronics',
 'Engineer, biomedical',
 'Chemical engineer',
 'Network engineer',
 'Mining engineer',
 'Engineer, electrical',
 'Chemical engineer',
 'Production engineer',
 'Engineer, broadcasting (operations)',
 'Aeronautical engineer',
 'Petroleum engineer',
 'Building services engineer',
 'Engineer, maintenance',
 'Civil engineer, contracting',
 'Engineer, energy',
 'Mechanical engineer',
 'Engineer, mining',
 'Energy engineer',
 'Technical sales engineer',
 'Engineer, maintenance (IT)',
 'Electrical engineer',
 'Materials engineer',
 'Communications engineer',
 'Communications engineer',
 'Engineer, maintenance',
 'Manufacturing engineer',
 'Engineer, automotive',
 'Engineer, maintenance',
 'Engineer, energy',
 'Automotive engineer',
 'Engineer, maintenance (IT)',
 'Production engineer',
 'Structural engineer',
 'Engineer, manufacturing systems',
 'Engineer, manufacturing',
 'Engineer, structural',
 'Structural engineer',
 'Energy engineer',
 'Engineer, maintenance (IT)',
 'Engineer, electronics',
 'Site engineer',
 'Aeronautical engineer',
 'Engineer, site',
 'Civil engineer, consulting',
 'Electronics engineer',
 'Engineer, manufacturing',
 'Chemical engineer',
 'Electrical engineer',
 'Engineer, civil (consulting)',
 'Technical sales engineer',
 'Engineer, production',
 'Civil engineer, contracting',
 'Engineer, electrical',
 'Engineer, electrical',
 'Broadcast engineer',
 'Civil engineer, consulting',
 'Engineer, energy',
 'Software engineer',
 'Communications engineer',
 'Biomedical engineer',
 'Engineer, mining',
 'Engineer, communications',
 'Agricultural engineer',
 'Civil engineer, consulting',
 'Structural engineer',
 'Manufacturing engineer',
 'Civil engineer, contracting',
 'Engineer, materials',
 'Automotive engineer',
 'Engineer, communications',
 'Mining engineer',
 'Engineer, site',
 'Manufacturing engineer',
 'Agricultural engineer',
 'Engineer, land',
 'Engineer, manufacturing',
 'Engineer, biomedical',
 'Engineer, civil (contracting)',
 'Engineer, mining',
 'Engineer, aeronautical',
 'Engineer, automotive',
 'Civil engineer, contracting',
 'Engineer, materials',
 'Engineer, manufacturing',
 'Civil engineer, consulting',
 'Engineer, structural',
 'Agricultural engineer',
 'Engineer, manufacturing systems',
 'Aeronautical engineer',
 'Contracting civil engineer',
 'Engineer, water',
 'Manufacturing systems engineer',
 'Automotive engineer',
 'Engineer, electronics',
 'Automotive engineer',
 'Engineer, control and instrumentation',
 'Engineer, aeronautical',
 'Engineer, structural',
 'Engineer, structural',
 'Engineer, maintenance (IT)',
 'Mining engineer',
 'Network engineer',
 'Engineer, water',
 'Mining engineer',
 'Materials engineer',
 'Technical sales engineer',
 'Engineer, maintenance (IT)',
 'Engineer, production',
 'Engineer, structural',
 'Maintenance engineer',
 'Engineer, structural',
 'Automotive engineer',
 'Engineer, structural',
 'Chemical engineer',
 'Structural engineer',
 'Electrical engineer',
 'Engineer, manufacturing',
 'Water engineer',
 'Engineer, electrical',
 'Production engineer',
 'Engineer, chemical',
 'Mechanical engineer',
 'Consulting civil engineer',
 'Chemical engineer',
 'Mechanical engineer',
 'Energy engineer',
 'Engineer, biomedical',
 'Network engineer',
 'Engineer, land',
 'Maintenance engineer',
 'Engineer, electrical',
 'Engineer, aeronautical',
 'Contracting civil engineer',
 'Engineer, agricultural',
 'Engineer, electronics',
 'Engineer, materials',
 'Drilling engineer',
 'Control and instrumentation engineer',
 'Network engineer',
 'Manufacturing engineer',
 'Engineer, communications',
 'Water engineer',
 'Engineer, broadcasting (operations)',
 'Engineer, control and instrumentation',
 'Communications engineer',
 'Software engineer',
 'Civil engineer, contracting',
 'Materials engineer',
 'Engineer, materials',
 'Materials engineer',
 'Engineer, civil (contracting)',
 'Biomedical engineer',
 'Electrical engineer',
 'Maintenance engineer',
 'Engineer, civil (contracting)',
 'Engineer, water',
 'Civil engineer, contracting',
 'Building services engineer',
 'Structural engineer',
 'Engineer, civil (contracting)',
 'Engineer, electrical',
 'Engineer, building services',
 'Building services engineer',
 'Mining engineer',
 'Maintenance engineer',
 'Engineer, building services',
 'Engineer, maintenance',
 'Engineer, mining',
 'Engineer, biomedical',
 'Engineer, manufacturing systems',
 'Electronics engineer',
 'Engineer, mining',
 'Broadcast engineer',
 'Biomedical engineer',
 'Structural engineer',
 'Automotive engineer',
 'Engineer, broadcasting (operations)',
 'Biomedical engineer',
 'Contracting civil engineer',
 'Manufacturing systems engineer',
 'Engineer, drilling',
 'Energy engineer',
 'Automotive engineer',
 'Engineer, technical sales',
 'Engineer, manufacturing systems',
 'Contracting civil engineer',
 'Biomedical engineer',
 'Engineer, chemical',
 'Consulting civil engineer',
 'Engineer, electronics',
 'Engineer, communications',
 'Communications engineer',
 'Network engineer',
 'Drilling engineer',
 'Electronics engineer',
 'Engineer, chemical',
 'Engineer, electronics',
 'Chemical engineer',
 'Civil engineer, consulting',
 'Engineer, electrical',
 'Engineer, civil (contracting)',
 'Engineer, automotive',
 'Engineer, technical sales',
 'Automotive engineer',
 'Automotive engineer',
 'Consulting civil engineer',
 'Building services engineer',
 'Manufacturing systems engineer',
 'Engineer, aeronautical',
 'Engineer, site',
 'Engineer, manufacturing',
 'Chemical engineer',
 'Engineer, building services',
 'Water engineer',
 'Engineer, automotive',
 'Engineer, maintenance',
 'Engineer, drilling',
 'Engineer, agricultural',
 'Drilling engineer',
 'Mechanical engineer',
 'Aeronautical engineer',
 'Engineer, electronics',
 'Engineer, maintenance (IT)',
 'Engineer, communications',
 'Civil engineer, contracting',
 'Building services engineer',
 'Civil engineer, contracting',
 'Network engineer',
 'Control and instrumentation engineer',
 'Biomedical engineer',
 'Network engineer',
 'Electronics engineer',
 'Technical sales engineer',
 'Engineer, communications',
 'Engineer, land',
 'Engineer, control and instrumentation',
 'Technical sales engineer',
 'Engineer, aeronautical',
 'Agricultural engineer',
 'Engineer, agricultural',
 'Water engineer',
 'Engineer, drilling',
 'Engineer, communications',
 'Engineer, land',
 'Engineer, materials',
 'Engineer, structural',
 'Water engineer',
 'Control and instrumentation engineer',
 'Electrical engineer',
 'Production engineer',
 'Aeronautical engineer',
 'Electrical engineer',
 'Electrical engineer',
 'Engineer, chemical',
 'Engineer, electronics',
 'Engineer, electrical',
 'Engineer, broadcasting (operations)',
 'Engineer, aeronautical',
 'Engineer, manufacturing systems',
 'Water engineer',
 'Engineer, land',
 'Engineer, civil (contracting)',
 'Engineer, automotive',
 'Manufacturing engineer',
 'Civil engineer, consulting',
 'Electronics engineer',
 'Control and instrumentation engineer',
 'Engineer, civil (consulting)',
 'Engineer, broadcasting (operations)',
 'Engineer, broadcasting (operations)',
 'Engineer, technical sales',
 'Engineer, building services',
 'Automotive engineer',
 'Biomedical engineer',
 'Building services engineer',
 'Engineer, biomedical',
 'Control and instrumentation engineer',
 'Engineer, petroleum',
 'Engineer, production',
 'Materials engineer',
 'Communications engineer',
 'Engineer, agricultural',
 'Engineer, land',
 'Electrical engineer',
 'Electronics engineer',
 'Engineer, civil (contracting)',
 'Biomedical engineer',
 'Energy engineer',
 'Materials engineer',
 'Engineer, control and instrumentation',
 'Engineer, water',
 'Engineer, site',
 'Mechanical engineer',
 'Contracting civil engineer',
 'Engineer, aeronautical',
 'Automotive engineer',
 'Automotive engineer',
 'Engineer, water',
 'Drilling engineer',
 'Automotive engineer',
 'Engineer, building services',
 'Chemical engineer',
 'Engineer, water',
 'Petroleum engineer',
 'Engineer, structural',
 'Mining engineer',
 'Mechanical engineer',
 'Structural engineer',
 'Structural engineer',
 'Engineer, civil (consulting)',
 'Maintenance engineer',
 'Agricultural engineer',
 'Drilling engineer',
 'Engineer, materials',
 'Drilling engineer',
 'Engineer, chemical',
 'Water engineer',
 'Civil engineer, contracting',
 'Electrical engineer',
 'Engineer, control and instrumentation',
 'Engineer, energy',
 'Electrical engineer',
 'Mining engineer',
 'Contracting civil engineer',
 'Engineer, energy',
 'Engineer, land',
 'Engineer, water',
 'Production engineer',
 'Broadcast engineer',
 'Engineer, building services',
 'Network engineer',
 'Software engineer',
 'Biomedical engineer',
 'Engineer, chemical',
 'Engineer, automotive',
 'Software engineer',
 'Engineer, energy',
 'Building services engineer',
 'Network engineer',
 'Aeronautical engineer',
 'Engineer, mining',
 'Engineer, building services',
 'Engineer, technical sales',
 'Engineer, manufacturing systems',
 'Materials engineer',
 'Engineer, technical sales',
 'Manufacturing systems engineer',
 'Water engineer',
 'Engineer, materials',
 'Civil engineer, contracting',
 'Engineer, water',
 'Consulting civil engineer',
 'Materials engineer',
 'Engineer, water',
 'Software engineer',
 'Contracting civil engineer',
 'Engineer, maintenance (IT)',
 'Engineer, maintenance (IT)',
 'Engineer, energy',
 'Engineer, broadcasting (operations)',
 'Engineer, broadcasting (operations)',
 'Engineer, building services',
 'Maintenance engineer',
 'Engineer, manufacturing systems',
 'Electronics engineer',
 'Structural engineer',
 'Engineer, electrical',
 'Engineer, petroleum',
 'Engineer, maintenance',
 'Materials engineer',
 'Engineer, land',
 'Engineer, drilling',
 'Drilling engineer',
 'Mechanical engineer',
 'Engineer, site',
 'Control and instrumentation engineer',
 'Chemical engineer',
 'Manufacturing engineer',
 'Engineer, aeronautical',
 'Engineer, petroleum',
 'Engineer, agricultural',
 'Consulting civil engineer',
 'Engineer, chemical',
 'Water engineer',
 'Mechanical engineer',
 'Engineer, manufacturing',
 'Petroleum engineer',
 'Communications engineer',
 'Engineer, automotive',
 'Communications engineer',
 'Consulting civil engineer',
 'Engineer, mining',
 'Mining engineer',
 'Structural engineer',
 'Engineer, structural',
 'Structural engineer',
 'Biomedical engineer',
 'Engineer, mining',
 'Engineer, petroleum',
 'Automotive engineer',
 'Engineer, electrical',
 'Engineer, electronics',
 'Engineer, aeronautical',
 'Civil engineer, contracting',
 'Engineer, broadcasting (operations)',
 'Engineer, manufacturing',
 'Engineer, maintenance',
 'Engineer, maintenance',
 'Building services engineer',
 'Engineer, land',
 'Engineer, drilling',
 'Engineer, electrical',
 'Engineer, structural',
 'Engineer, maintenance',
 'Civil engineer, contracting',
 'Engineer, site',
 'Engineer, water',
 'Engineer, petroleum',
 'Network engineer',
 'Engineer, production',
 'Network engineer',
 'Mechanical engineer',
 'Site engineer',
 'Site engineer',
 'Engineer, biomedical',
 'Network engineer',
 'Engineer, communications',
 'Network engineer',
 'Engineer, automotive',
 'Engineer, civil (contracting)',
 'Production engineer',
 'Structural engineer',
 'Engineer, biomedical',
 'Mining engineer',
 'Production engineer',
 'Engineer, communications',
 'Engineer, broadcasting (operations)',
 'Materials engineer',
 'Engineer, land',
 'Engineer, agricultural',
 'Mining engineer',
 'Engineer, production',
 'Engineer, maintenance (IT)',
 'Engineer, maintenance (IT)',
 'Engineer, broadcasting (operations)',
 'Consulting civil engineer',
 'Site engineer',
 'Engineer, electrical',
 'Engineer, materials',
 'Petroleum engineer',
 'Electrical engineer',
 'Engineer, agricultural',
 'Control and instrumentation engineer',
 'Agricultural engineer',
 'Energy engineer',
 'Engineer, water',
 'Engineer, mining',
 'Engineer, chemical',
 'Engineer, electronics',
 'Engineer, agricultural',
 'Engineer, petroleum',
 'Production engineer',
 'Civil engineer, contracting',
 'Energy engineer',
 'Production engineer',
 'Engineer, land',
 'Civil engineer, contracting',
 'Software engineer',
 'Structural engineer',
 'Communications engineer',
 'Chemical engineer',
 'Engineer, civil (consulting)',
 'Civil engineer, contracting',
 'Automotive engineer',
 'Engineer, control and instrumentation',
 'Engineer, building services',
 'Structural engineer',
 'Engineer, automotive',
 'Site engineer',
 'Control and instrumentation engineer',
 'Materials engineer',
 'Engineer, electronics',
 'Engineer, water',
 'Biomedical engineer',
 'Engineer, production',
 'Manufacturing systems engineer',
 'Engineer, building services',
 'Engineer, manufacturing',
 'Engineer, structural',
 'Engineer, building services',
 'Civil engineer, contracting',
 'Technical sales engineer',
 'Engineer, aeronautical',
 'Contracting civil engineer',
 'Engineer, aeronautical',
 'Engineer, building services',
 'Engineer, aeronautical',
 'Engineer, biomedical',
 'Manufacturing systems engineer',
 'Electronics engineer',
 'Engineer, petroleum',
 'Technical sales engineer',
 'Software engineer',
 'Engineer, materials',
 'Drilling engineer',
 'Engineer, production',
 'Engineer, building services',
 'Contracting civil engineer',
 'Engineer, water',
 'Engineer, site',
 'Engineer, energy',
 'Technical sales engineer',
 'Technical sales engineer',
 'Automotive engineer',
 'Maintenance engineer',
 'Agricultural engineer',
 'Petroleum engineer',
 'Engineer, agricultural',
 'Mining engineer',
 'Engineer, petroleum',
 'Petroleum engineer',
 'Engineer, structural',
 'Electronics engineer',
 'Electrical engineer',
 'Engineer, manufacturing',
 'Electrical engineer',
 'Biomedical engineer',
 'Production engineer',
 'Broadcast engineer',
 'Engineer, land',
 'Engineer, energy',
 'Engineer, water',
 'Technical sales engineer',
 'Engineer, automotive',
 'Engineer, agricultural',
 'Aeronautical engineer',
 'Network engineer',
 'Engineer, maintenance',
 'Consulting civil engineer',
 'Engineer, automotive',
 'Mining engineer',
 'Water engineer',
 'Engineer, manufacturing',
 'Engineer, communications',
 'Engineer, technical sales',
 'Engineer, biomedical',
 'Mining engineer',
 'Automotive engineer',
 'Mining engineer',
 'Communications engineer',
 'Site engineer',
 'Broadcast engineer',
 'Maintenance engineer',
 'Engineer, agricultural',
 'Electrical engineer',
 'Engineer, civil (contracting)',
 'Petroleum engineer',
 'Petroleum engineer',
 'Electronics engineer',
 'Site engineer',
 'Production engineer',
 'Engineer, drilling',
 'Engineer, civil (contracting)',
 'Civil engineer, contracting',
 'Biomedical engineer',
 'Software engineer',
 'Contracting civil engineer',
 'Engineer, biomedical',
 'Engineer, maintenance',
 'Engineer, water',
 'Manufacturing systems engineer',
 'Aeronautical engineer',
 'Maintenance engineer',
 'Broadcast engineer',
 'Engineer, biomedical',
 'Engineer, site',
 'Mining engineer',
 'Engineer, drilling',
 'Engineer, drilling',
 'Engineer, electrical',
 'Engineer, broadcasting (operations)',
 'Engineer, water',
 'Communications engineer',
 'Electronics engineer',
 'Engineer, chemical',
 'Engineer, building services',
 'Network engineer',
 'Petroleum engineer',
 'Electrical engineer',
 'Materials engineer',
 'Petroleum engineer',
 'Engineer, broadcasting (operations)',
 'Engineer, aeronautical',
 'Engineer, water',
 'Engineer, water',
 'Contracting civil engineer',
 'Chemical engineer',
 'Mining engineer',
 'Engineer, control and instrumentation',
 'Site engineer',
 'Civil engineer, contracting',
 'Engineer, water',
 'Drilling engineer',
 'Engineer, land',
 'Petroleum engineer',
 'Aeronautical engineer',
 'Manufacturing engineer',
 'Petroleum engineer',
 'Civil engineer, consulting',
 'Energy engineer',
 'Maintenance engineer',
 'Aeronautical engineer',
 'Petroleum engineer',
 'Engineer, electrical',
 'Electrical engineer',
 'Engineer, water',

### Qn 6
- Find the email of the person with the IP address: 132.207.160.22.

In [36]:
df_132_207_160_22 = ecom_df[ecom_df['IP Address'] == '132.207.160.22'][['Email', 'IP Address']]
df_132_207_160_22

                            Email      IP Address
2  amymiller@morales-harrison.com  132.207.160.22

### Qn 7
- Find the email of the person with the Credit Card Number: 4664825258997302.

In [38]:
df_4664825258997302 = ecom_df[ecom_df['Credit Card'] == 4664825258997302][['Email', 'Credit Card']]
df_4664825258997302

                  Email       Credit Card
9992  bberry@wright.net  4664825258997302

## Qn 8
- How many people have a credit card that expires in 2020?

In [ ]:
df_2020 = ecom_df[ecom_df['CC Exp Date'].str.contains('/20')]
df_2020

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
19,"125 Hall Summit\nBoothton, IL 41721",99 CU,PM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Turner-Mckinney,676343504830,02/20,440,VISA 16 digit,ruiznicole@gmail.com,"Designer, interior/spatial",25.105.209.214,fr,58.39
32,Unit 3628 Box 6778\nDPO AE 72362,39 Qm,PM,Mozilla/5.0 (Windows 98; Win 9x 4.90) AppleWeb...,Martinez-Wilson,4942281854569455,01/20,8360,JCB 16 digit,shane21@atkinson.com,Civil Service fast streamer,196.37.134.217,pt,56.63
36,"9374 Skinner Common Apt. 254\nChristopherfort,...",80 Fq,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Hanna-Grant,180042289507877,09/20,912,VISA 16 digit,saundersernest@walsh.com,Animal technologist,85.134.58.250,zh,9.77
38,"9671 Riley Drives Apt. 746\nPort Davidtown, TN...",15 vj,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,"Bryant, Hubbard and Gonzales",210094965373094,12/20,248,Voyager,djennings@boyd-english.org,Music therapist,143.138.65.219,en,30.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9883,"751 Petersen Groves\nLake Rebecca, NM 55875",61 tE,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_7...,Perez and Sons,4939814860063025,05/20,238,Mastercard,lisa25@hotmail.com,Therapeutic radiographer,215.85.159.70,pt,67.47
9901,"908 Norman Burgs\nPhillipsberg, VT 92023-9956",90 Ng,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Hughes Inc,30148833294789,09/20,483,Voyager,james32@gmail.com,Meteorologist,250.66.85.29,en,57.25
9911,"44320 Gray Centers Suite 325\nJenniferfurt, OK...",19 Bf,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,Jones-Gray,4058074716188,12/20,921,Diners Club / Carte Blanche,hensonlindsay@graves-fox.com,"Optician, dispensing",84.118.30.56,en,20.63
9957,"73556 Chase Pine\nBrucemouth, MP 73473",25 rU,PM,Opera/9.49.(Windows 95; en-US) Presto/2.9.189 ...,"Martin, Clayton and Jarvis",3337737293232646,05/20,798,VISA 13 digit,latashaochoa@gmail.com,Therapeutic radiographer,239.219.241.162,ru,71.85
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96

### Qn 9 
- What are the top 5 most popular email providers (e.g., Gmail, Yahoo)?

In [55]:
ecom_df['email_domain'] = ecom_df['Email'].str.split('@').str[1]
ecom_df

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,email_domain
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,yahoo.com
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73,reed.com
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95,morales-harrison.com
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04,olson-robinson.info
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82,gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21,wade-garner.com
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63,hotmail.com
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98,gmail.com
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84,reid.net
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59,vaughn.com

In [76]:
email_df = ecom_df.groupby('email_domain')['Email'].count().reset_index()
email_df.rename(columns={'Email': 'count'}, inplace=True)
email_df = email_df.sort_values(by='count', ascending=False)
email_df.head(5)

      email_domain  count
1397   hotmail.com   1638
3384     yahoo.com   1616
1053     gmail.com   1605
2868     smith.com     42
3306  williams.com     37

### Qn 10
- How many unique job titles are there?

In [85]:
unique_job_titles = ecom_df['Job'].nunique()
print(unique_job_titles)

623

### Qn 11
- Find the most common job title in the dataset.

In [83]:
job_df = ecom_df.groupby('Job')['Address'].count().reset_index()
job_df.rename(columns={'Address': 'count'}, inplace=True)
job_df = job_df.sort_values(by='count', ascending=False)
job_df

                                   Job  count
312      Interior and spatial designer     31
325                             Lawyer     30
531                  Social researcher     28
151                Designer, jewellery     27
489  Research officer, political party     27
..                                 ...    ...
379                    Music therapist      7
169                 Editor, film/video      6
8                              Actuary      6
315                 Investment analyst      5
305        Information systems manager      5

[623 rows x 2 columns]

### Qn 12
- Find the number of people using a "JCB 16 digit" credit card provider.

In [67]:
df_JCB_16 = ecom_df[ecom_df['CC Provider'].str.contains('JCB 16')]
df_JCB_16

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,email_domain
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,yahoo.com
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95,morales-harrison.com
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54,rasmussen.com
21,"282 Miller Valleys Suite 404\nWilkinsonbury, M...",24 RZ,AM,Mozilla/5.0 (compatible; MSIE 6.0; Windows NT ...,Guzman-Reese,5491255326230898,03/25,506,JCB 16 digit,rsmith@hotmail.com,"Presenter, broadcasting",125.58.66.253,it,90.93,hotmail.com
32,Unit 3628 Box 6778\nDPO AE 72362,39 Qm,PM,Mozilla/5.0 (Windows 98; Win 9x 4.90) AppleWeb...,Martinez-Wilson,4942281854569455,01/20,8360,JCB 16 digit,shane21@atkinson.com,Civil Service fast streamer,196.37.134.217,pt,56.63,atkinson.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9979,"00490 Joseph Haven Apt. 149\nWest Keithfurt, S...",69 XK,PM,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/5311 ...,Randall-Ramirez,346734838013255,10/23,224,JCB 16 digit,qjohnson@yahoo.com,Lawyer,17.76.83.105,en,14.55,yahoo.com
9982,"18044 Mcintosh Row Apt. 122\nLake Jennifer, NC...",77 uq,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_6_0...,Chen LLC,210040992311995,09/18,79,JCB 16 digit,heather24@gmail.com,Restaurant manager,93.254.124.2,it,56.25,gmail.com
9983,"PSC 5678, Box 4503\nAPO AP 94998-5546",79 cd,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Hall-Cantu,343856674589081,04/23,206,JCB 16 digit,jacksonmanuel@rodriguez-welch.com,"Scientist, research (life sciences)",245.22.66.225,de,47.70,rodriguez-welch.com
9986,"2719 Troy Drive Suite 062\nLisachester, PW 414...",80 Wl,PM,Mozilla/5.0 (Windows NT 5.2; sl-SI; rv:1.9.1.2...,Campbell-Hurley,4220882411745414,08/18,460,JCB 16 digit,belindaleon@schwartz.com,Cabin crew,110.103.102.55,it,22.02,schwartz.com
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63,hotmail.com