In [2]:
import pandas as pd

### Qn 1 
- Reading CSV File

In [5]:
df = pd.read_csv('../Pandas/sample_data/sales_data.csv')
df.head()

,order_id,report_date,customer_name,order_level,shipping_type,area,province,city,product_type,product_sub_type,product_name,product_box,order_number,order_amt,back_point,profit_amt,price,shipping_cost,shipping_date
0,225,2022/8/14 00:00,Ali,L1,Plain,Center,Hunan,Changsha,Office,Paper,Kleencut_ Forged Office Shears by Acme United ...,Small Box,42,229.8800,0.05,-75.25,5.28,5.06,2022/8/15 00:00
1,420,2023/1/20 00:00,Ali,L1,Plain,Northwest,Shanxi,Baoji,Office,Pen,Kleencut_ Forged Office Shears by Acme United ...,Paperbag,50,99.0800,0.01,11.28,1.76,0.70,2023/1/20 00:00
2,548,2020/12/11 00:00,Ali,L1,Train,Center,Henan,Zhengzhou,Technique,Accessory,Kleencut_ Forged Office Shears by Acme United ...,Small bag,66,2876.7700,0.09,-1078.79,88.06,56.10,2020/12/13 00:00
3,1028,2020/3/28 00:00,Ali,L1,Train,Center,Henan,Zhumadian,Technique,Telephone,Kleencut_ Forged Office Shears by Acme United ...,Small bag,30,932.8920,0.05,458.98,35.99,0.99,2020/3/30 00:00
4,2307,2021/9/18 00:00,Ali,L1,Train,East,Zhejiang,Quzhou,Technique,Accessory,Kleencut_ Forged Office Shears by Acme United ...,Small Box,39,4226.3125,0.15,495.65,259.97,10.76,2021/9/18 00:00

### Q2
- Find all orders where order_amt is greater than 500.

In [7]:
df_gtr_500 = df[df['order_amt'] > 500]
df_gtr_500

,order_id,report_date,customer_name,order_level,shipping_type,area,province,city,product_type,product_sub_type,product_name,product_box,order_number,order_amt,back_point,profit_amt,price,shipping_cost,shipping_date
2,548,2020/12/11 00:00,Ali,L1,Train,Center,Henan,Zhengzhou,Technique,Accessory,Kleencut_ Forged Office Shears by Acme United ...,Small bag,66,2876.7700,0.09,-1078.79,88.06,56.10,2020/12/13 00:00
3,1028,2020/3/28 00:00,Ali,L1,Train,Center,Henan,Zhumadian,Technique,Telephone,Kleencut_ Forged Office Shears by Acme United ...,Small bag,30,932.8920,0.05,458.98,35.99,0.99,2020/3/30 00:00
4,2307,2021/9/18 00:00,Ali,L1,Train,East,Zhejiang,Quzhou,Technique,Accessory,Kleencut_ Forged Office Shears by Acme United ...,Small Box,39,4226.3125,0.15,495.65,259.97,10.76,2021/9/18 00:00
6,5281,2023/1/22 00:00,Ali,L1,Train,East,Zhejiang,Zhoushan,Technique,Accessory,Kleencut_ Forged Office Shears by Acme United ...,Small Box,38,1438.1900,0.13,155.68,107.46,14.67,2023/1/23 00:00
7,5446,2020/9/10 00:00,Ali,L1,Train,North,Neimenggu,Wulanchabu,Office,Appliance,Kleencut_ Forged Office Shears by Acme United ...,Small Box,123,3110.4600,0.31,471.48,142.46,24.61,2020/9/17 00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,15907,2022/7/2 00:00,Collins,L1,Train,Center,Hunan,Zhuzhou,Furniture,Decorator,Kleencut_ Forged Office Shears by Acme United ...,Large Box,8,1604.5200,0.03,-213.71,297.97,83.92,2022/7/5 00:00
992,15972,2022/10/30 00:00,Collins,L1,Train,East,Shandong,Liaocheng,Furniture,Decorator,Kleencut_ Forged Office Shears by Acme United ...,Medium Box,43,2387.6100,0.01,527.13,54.20,11.10,2022/10/31 00:00
993,16005,2024/3/16 00:00,Collins,L1,Train,East,Shandong,Qingdao,Office,band,Kleencut_ Forged Office Shears by Acme United ...,Paperbag,127,2019.7800,0.18,365.98,48.06,10.39,2024/3/18 00:00
995,16519,2022/8/31 00:00,Collins,L1,Train,East,Zhejiang,Quzhou,Technique,Telephone,Kleencut_ Forged Office Shears by Acme United ...,Small bag,57,2081.7495,0.09,289.42,84.35,23.09,2022/9/2 00:00
998,17255,2021/10/4 00:00,Collins,L1,Train,North,Beijing,Beijing,Technique,Telephone,Kleencut_ Forged Office Shears by Acme United ...,Small Box,8,1391.7645,0.08,-426.07,205.99,8.99,2021/10/5 00:00

### Q3
- Sort the DataFrame by profit_amt

In [8]:
df_sorted = df.sort_values(by="profit_amt", ascending=False)
df_sorted.head()

,order_id,report_date,customer_name,order_level,shipping_type,area,province,city,product_type,product_sub_type,product_name,product_box,order_number,order_amt,back_point,profit_amt,price,shipping_cost,shipping_date
562,59559,2021/12/8 00:00,Blake,L1,Train,Northwest,Ningxia,Yinchuan,Office,Appliance,Kleencut_ Forged Office Shears by Acme United ...,Large Box,82,33902.363,0.09,12663.41,1537.96,77.98,2021/12/8 00:00
14,10117,2022/2/6 00:00,Ali,L1,Train,South,Guangdong,Guangzhou,Office,undefined,Kleencut_ Forged Office Shears by Acme United ...,Small Box,18,23792.930,0.00,10951.31,1270.99,19.99,2022/2/7 00:00
580,258,2022/3/20 00:00,Blake,L2,Train,North,Neimenggu,Huhehaote,Office,undefined,Kleencut_ Forged Office Shears by Acme United ...,Small Box,25,21752.010,0.03,9296.35,896.99,19.99,2022/3/21 00:00
144,10306,2021/10/11 00:00,Barker,L1,Truck,East,Zhejiang,Quzhou,Technique,Machines,Kleencut_ Forged Office Shears by Acme United ...,Huge Box,35,25313.340,0.05,8612.11,810.98,16.06,2021/10/11 00:00
235,13861,2021/11/1 00:00,Barrett,L1,Train,Northeast,Liaoning,Liaoyang,Office,undefined,Kleencut_ Forged Office Shears by Acme United ...,Small Box,44,22172.480,0.09,8416.24,1363.22,59.60,2021/11/1 00:00

### Qn 4
- Find the total order_amt for each province.

In [9]:
sales_by_province = df.groupby("province")["order_amt"].sum().reset_index()
sales_by_province

        province    order_amt
0          Anhui   93202.5095
1        Beijing   85326.6855
2         Fujian   57479.5890
3          Gansu   89536.2860
4      Guangdong  442881.6465
5        Guangxi  176457.1065
6        Guizhou    7824.5385
7         Hainan  197520.0695
8          Hebei   48033.6000
9   Heilongjiang  128051.4780
10         Henan  186411.3540
11         Hubei  254909.3645
12         Hunan   48792.3915
13       Jiangsu   29058.7620
14       Jiangxi   32251.1700
15         Jilin  131911.4380
16      Liaoning  240196.8155
17     Neimenggu  138483.6750
18       Ningxia   75378.7580
19       Qinghai     648.7495
20      Shandong   46805.2840
21      Shanghai   13457.0180
22        Shanxi  119845.1570
23       Sichuan    5584.4840
24       Tianjin   56280.2315
25        Xicang    4121.5675
26      Xinjiang   11824.2800
27      Zhejiang  248206.8555
28     Zhongqing    6978.2970

### Qn 5
- Get a list of unique product_type values in the dataset.

In [10]:
df_unique_product = df['product_type'].unique()
df_unique_product

array(['Office', 'Technique', 'Furniture'], dtype=object)

### Qn 6
- Count and display the number of missing values in each column.

In [11]:
df_missing = df.isna().sum()
df_missing

order_id            0
report_date         0
customer_name       0
order_level         0
shipping_type       0
area                0
province            0
city                0
product_type        0
product_sub_type    0
product_name        0
product_box         0
order_number        0
order_amt           0
back_point          0
profit_amt          0
price               0
shipping_cost       0
shipping_date       0
dtype: int64

### Qn 7
- Filter out all orders placed in the year 2022.

In [12]:
df_2022 =df[pd.to_datetime(df['report_date']).dt.year == 2022]
df_2022

,order_id,report_date,customer_name,order_level,shipping_type,area,province,city,product_type,product_sub_type,product_name,product_box,order_number,order_amt,back_point,profit_amt,price,shipping_cost,shipping_date
0,225,2022/8/14 00:00,Ali,L1,Plain,Center,Hunan,Changsha,Office,Paper,Kleencut_ Forged Office Shears by Acme United ...,Small Box,42,229.8800,0.05,-75.25,5.28,5.06,2022/8/15 00:00
11,9127,2022/12/31 00:00,Ali,L1,Train,Northeast,Jilin,Songyuan,Office,undefined,Kleencut_ Forged Office Shears by Acme United ...,Small Box,22,138.2400,0.06,-48.22,6.37,5.19,2023/1/2 00:00
14,10117,2022/2/6 00:00,Ali,L1,Train,South,Guangdong,Guangzhou,Office,undefined,Kleencut_ Forged Office Shears by Acme United ...,Small Box,18,23792.9300,0.00,10951.31,1270.99,19.99,2022/2/7 00:00
24,14789,2022/2/19 00:00,Ali,L1,Truck,Northeast,Liaoning,Dalian,Furniture,Table,Kleencut_ Forged Office Shears by Acme United ...,Huge Paperbag,57,8421.5720,0.13,1834.46,289.65,39.17,2022/2/21 00:00
32,24646,2022/7/6 00:00,Ali,L2,Train,Center,Hubei,Jingzhou,Furniture,Decorator,Kleencut_ Forged Office Shears by Acme United ...,Large Box,62,13159.5400,0.03,3755.90,404.14,32.75,2022/7/8 00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,16481,2022/5/11 00:00,Collins,L1,Train,East,Zhejiang,Hangzhou,Office,undefined,Kleencut_ Forged Office Shears by Acme United ...,Small Box,23,107.9300,0.00,-68.14,4.13,5.34,2022/5/16 00:00
995,16519,2022/8/31 00:00,Collins,L1,Train,East,Zhejiang,Quzhou,Technique,Telephone,Kleencut_ Forged Office Shears by Acme United ...,Small bag,57,2081.7495,0.09,289.42,84.35,23.09,2022/9/2 00:00
996,17252,2022/7/20 00:00,Collins,L1,Train,East,Zhejiang,Taizhou,Office,Paper,Kleencut_ Forged Office Shears by Acme United ...,Small Box,10,315.4200,0.10,-41.26,30.98,17.08,2022/7/22 00:00
997,17253,2022/11/7 00:00,Collins,L1,Train,North,Beijing,Beijing,Office,Pen,Kleencut_ Forged Office Shears by Acme United ...,Paperbag,28,164.5000,0.01,62.68,5.84,1.00,2022/11/9 00:00
999,17958,2022/11/1 00:00,Collins,L1,Train,North,Shanxi,Taiyuan,Office,undefined,Kleencut_ Forged Office Shears by Acme United ...,Small Box,37,254.9300,0.01,-62.88,6.81,5.48,2022/11/5 00:00

### Qn 8
- Create a new column profit_margin calculated as (profit_amt / order_amt) * 100.

In [13]:
df['profit_mgn'] = df['profit_amt'] / df['order_amt'] * 100
df

,order_id,report_date,customer_name,order_level,shipping_type,area,province,city,product_type,product_sub_type,product_name,product_box,order_number,order_amt,back_point,profit_amt,price,shipping_cost,shipping_date,profit_mgn
0,225,2022/8/14 00:00,Ali,L1,Plain,Center,Hunan,Changsha,Office,Paper,Kleencut_ Forged Office Shears by Acme United ...,Small Box,42,229.8800,0.05,-75.25,5.28,5.06,2022/8/15 00:00,-32.734470
1,420,2023/1/20 00:00,Ali,L1,Plain,Northwest,Shanxi,Baoji,Office,Pen,Kleencut_ Forged Office Shears by Acme United ...,Paperbag,50,99.0800,0.01,11.28,1.76,0.70,2023/1/20 00:00,11.384740
2,548,2020/12/11 00:00,Ali,L1,Train,Center,Henan,Zhengzhou,Technique,Accessory,Kleencut_ Forged Office Shears by Acme United ...,Small bag,66,2876.7700,0.09,-1078.79,88.06,56.10,2020/12/13 00:00,-37.500043
3,1028,2020/3/28 00:00,Ali,L1,Train,Center,Henan,Zhumadian,Technique,Telephone,Kleencut_ Forged Office Shears by Acme United ...,Small bag,30,932.8920,0.05,458.98,35.99,0.99,2020/3/30 00:00,49.199693
4,2307,2021/9/18 00:00,Ali,L1,Train,East,Zhejiang,Quzhou,Technique,Accessory,Kleencut_ Forged Office Shears by Acme United ...,Small Box,39,4226.3125,0.15,495.65,259.97,10.76,2021/9/18 00:00,11.727718
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,16519,2022/8/31 00:00,Collins,L1,Train,East,Zhejiang,Quzhou,Technique,Telephone,Kleencut_ Forged Office Shears by Acme United ...,Small bag,57,2081.7495,0.09,289.42,84.35,23.09,2022/9/2 00:00,13.902729
996,17252,2022/7/20 00:00,Collins,L1,Train,East,Zhejiang,Taizhou,Office,Paper,Kleencut_ Forged Office Shears by Acme United ...,Small Box,10,315.4200,0.10,-41.26,30.98,17.08,2022/7/22 00:00,-13.080971
997,17253,2022/11/7 00:00,Collins,L1,Train,North,Beijing,Beijing,Office,Pen,Kleencut_ Forged Office Shears by Acme United ...,Paperbag,28,164.5000,0.01,62.68,5.84,1.00,2022/11/9 00:00,38.103343
998,17255,2021/10/4 00:00,Collins,L1,Train,North,Beijing,Beijing,Technique,Telephone,Kleencut_ Forged Office Shears by Acme United ...,Small Box,8,1391.7645,0.08,-426.07,205.99,8.99,2021/10/5 00:00,-30.613656
999,17958,2022/11/1 00:00,Collins,L1,Train,North,Shanxi,Taiyuan,Office,undefined,Kleencut_ Forged Office Shears by Acme United ...,Small Box,37,254.9300,0.01,-62.88,6.81,5.48,2022/11/5 00:00,-24.665594

### Qn 9
- Find the most common shipping_type used.

In [14]:
df_cmn_shipps = df['shipping_type'].value_counts()
df_cmn_shipps

shipping_type
Train    769
Truck    116
Plain    115
Name: count, dtype: int64

### Qn 10
- Create a pivot table showing the total order_amt for each province and city.

In [15]:
pvt_df = df.pivot_table(index=['province', 'city'], values='order_amt', aggfunc='sum')
pvt_df

                      order_amt
province  city
Anhui     Bangbu     12463.1625
          Bozhou      2665.8300
          Chuzhou    16858.5900
          Fuyang      5344.9000
          Hefei       3872.6340
...                         ...
Zhejiang  Shaoxing       7.9800
          Taizhou    53977.5675
          Wenzhou    27475.5170
          Zhoushan   15428.3900
Zhongqing Zhongqing   6978.2970

[205 rows x 1 columns]